from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('task', views.task, name="task"),
    path('task-allocated', views.taskAllocated, name="taskAllocated"),
    path('task-closed', views.taskClosed, name="taskClosed"),
    path('task-assess', views.taskAssess, name="taskAssess"),
    path('my-appraisal', views.myAppraisal, name="myAppraisal"),
    path('my-evaluation', views.myEvaluation, name="myEvaluation"),
    path('report-kpi-data', views.reportKPIData, name="reportKPIData"),
    path('performance-report', views.performanceReport, name="performanceReport"),
    path('kpi-report', views.kpiReport, name="kpiReport"),
    path('ifeel', views.iFeel, name="iFeel"),
    path('development-goals', views.developmentGoals, name="developmentGoals"),
    path('my-trainings', views.myTrainings, name="myTrainings"),
    path('create-task', views.createTask, name="createTask"),
    path('manager-evaluation', views.managerEvaluation, name="managerEvaluation"),
    path('owner-evaluation', views.ownerEvaluation, name="ownerEvaluation"),
    path('salary-report', views.salaryReport, name="salaryReport"),
    path('internal-projects', views.internalProjects, name="internalProjects"),
    path('strategic-goals', views.strategicGoals, name="strategicGoals"),
    path('mission', views.mission, name="mission"),
    path('organization-chart', views.organizationChart, name="organizationChart"),
    path('create-strategy', views.createStrategy, name="createStrategy"),
    path('create-internal-project', views.createInternalProject, name="createInternalProject"),
    path('employees', views.employees, name="employees"),
    path('departments', views.departments, name="departments"),
    path('create-new-department', views.createNewDepartment, name="createNewDepartment"),
    path('roles', views.roles, name="roles"),
    path('create-new-role', views.createNewRole, name="createNewRole"),
    path('job-requirements-kra', views.jobRequirementsKRA, name="jobRequirementsKRA"),
    path('create-new-job-requirement', views.createNewJobRequirement, name="createNewJobRequirement"),
    path('grades', views.grades, name="grades"),
    path('create-new-grade', views.createNewGrade, name="createNewGrade"),
    path('appraisal-cycle', views.appraisalCycle, name="appraisalCycle"),
    path('create-new-appraisal-cycle', views.createNewAppraisalCycle, name="createNewAppraisalCycle"),
    path('kpi', views.kpi, name="kpi"),
    path('create-new-kpi', views.createNewKPI, name="createNewKPI"),
    path('training-admin', views.trainingAdmin, name="trainingAdmin"),
    path('create-new-training', views.createNewTraining, name="createNewTraining"),
    path('trainers', views.trainers, name="trainers"),
    path('create-new-trainer', views.createNewTrainer, name="createNewTrainer"),
    path('topics', views.topics, name="topics"),
    path('create-new-topic', views.createNewTopic, name="createNewTopic"),
    path('person-wise-report', views.personWiseReport, name="personWiseReport"),
]